#!/usr/bin/env python3
"""Exact admissibility of the order-four filter as a function of the noise bound B.

phi_A(eta,lambda) = A*eta + lambda mod p must be injective on [-B,B]^2.
A collision is a nonzero (d,e) with |d|,|e| <= 2B and A*d = e (mod p), i.e. a
nonzero point of the lattice L = {(d,e) : A d = e mod p} inside [-2B,2B]^2.

Because A^2 = -1 (mod p), L is closed under the 90-degree rotation
(d,e) -> (-e,d), so L is the Gaussian-integer ideal generated by (a,b) where
p = a^2 + b^2.  Hence the minimum sup-norm over nonzero points is exactly
min over lattice points, which we compute by brute force over a safe range.

  B_max = floor((s_min - 1) / 2)   where s_min = min sup-norm of a nonzero point.
"""
import math

PRIMES = [1297, 1601, 2521, 2917, 3137, 4513, 7057, 8101, 13457, 14401, 15377, 65537]


def order4_radix(p):
    """smallest positive A with A^2 = -1 mod p (p = 1 mod 4)."""
    # A = g^((p-1)/4) for a generator g; brute force is fine at this size
    for a in range(2, p):
        if (a * a) % p == p - 1:
            return min(a, p - a)
    return None


def gaussian(p):
    """p = a^2 + b^2 with a >= b > 0."""
    for a in range(int(math.isqrt(p)), 0, -1):
        r = p - a * a
        b = math.isqrt(r)
        if b * b == r and b > 0:
            return a, b
    return None


def min_supnorm(p, A):
    """minimum sup-norm of a nonzero point of L = {(d,e): A d = e mod p}."""
    best = p
    # every lattice point with |d| <= bound is (d, ((A*d) mod p) centred)
    bound = int(2 * math.isqrt(p)) + 2
    for d in range(0, bound + 1):
        e = (A * d) % p
        if e > p // 2:
            e -= p
        if d == 0 and e == 0:
            continue
        s = max(abs(d), abs(e))
        if s < best:
            best = s
    return best


def B_of_h(h, ring):
    """B = ceil(k sqrt(h phi(M) 2^w / (12 M)) + 0.5) with k = 8, per MHWW24 Lemma 6.
    general (w=2, phi/M ~ 1): 8 sqrt(h/3) + 0.5 ; power-of-two (w=1, phi/M=1/2): 8 sqrt(h/12) + 0.5"""
    if ring == "general":
        return math.ceil(8 * math.sqrt(h / 3.0) + 0.5)
    return math.ceil(8 * math.sqrt(h / 12.0) + 0.5)


print("prime   A     p=a^2+b^2      s_min  B_max  |  (2B+1)^2<p would allow B<=")
print("-" * 84)
info = {}
for p in PRIMES:
    A = order4_radix(p)
    a, b = gaussian(p)
    s = min_supnorm(p, A)
    bmax = (s - 1) // 2
    naive = (int(math.isqrt(p - 1)) - 1) // 2   # largest B with (2B+1)^2 < p
    info[p] = (A, bmax)
    print("%-7d %-5d %5d^2+%-5d^2  %5d  %5d  |  %d" % (p, A, a, b, s, bmax, naive))

print()
print("Key weights and the resulting B (MHWW24 Lemma 6, k=8):")
for h in (12, 18, 24, 26, 40):
    print("  h=%-3d  general B=%-3d  power-of-two B=%d" % (h, B_of_h(h, "general"), B_of_h(h, "po2")))

print()
GEN = [1601, 2521, 2917, 4513, 8101, 13457, 14401, 15377, 65537]
PO2 = [1297, 1601, 2521, 3137, 4513, 7057, 13457, 14401, 15377, 65537]
for h in (12, 18, 24, 26):
    bg, bp = B_of_h(h, "general"), B_of_h(h, "po2")
    okg = [p for p in GEN if info[p][1] >= bg]
    okp = [p for p in PO2 if info[p][1] >= bp]
    print("h=%-3d  general B=%-3d -> %d/%d admissible %s" % (h, bg, len(okg), len(GEN),
          "" if len(okg) == len(GEN) else "(drops %s)" % [p for p in GEN if p not in okg]))
    print("       po2     B=%-3d -> %d/%d admissible %s" % (bp, len(okp), len(PO2),
          "" if len(okp) == len(PO2) else "(drops %s)" % [p for p in PO2 if p not in okp]))
