#!/usr/bin/env sage
"""
Extension-Field Mixed-Radix Homomorphic NTT: Correctness Verification

Verifies that the Mixed-Radix DIF decomposition of the 96-point Step2Matrix
produces the correct result when all stage matrices are multiplied together.

D = 96 = 32 × 3
Stage 1: Radix-3 DIF (stride 32), 3 diagonals at {0, 32, 64}
Stage 2-6: Radix-2 DIF (5 layers), each 2 diagonals at {0, stride}
Total: 3 + 5×2 = 13 diagonals across 6 stages
vs BSGS: 96 diagonals in 1 stage
"""


# This file was *autogenerated* from the file mixedradix_verify.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65537 = Integer(65537); _sage_const_97 = Integer(97); _sage_const_96 = Integer(96); _sage_const_50731 = Integer(50731); _sage_const_5 = Integer(5); _sage_const_70 = Integer(70); _sage_const_1 = Integer(1); _sage_const_43 = Integer(43); _sage_const_1461 = Integer(1461); _sage_const_58250 = Integer(58250); _sage_const_9157 = Integer(9157); _sage_const_9246 = Integer(9246); _sage_const_59875 = Integer(59875); _sage_const_13341 = Integer(13341); _sage_const_31936 = Integer(31936); _sage_const_43855 = Integer(43855); _sage_const_0 = Integer(0); _sage_const_18 = Integer(18); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_32 = Integer(32); _sage_const_64 = Integer(64); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_48 = Integer(48)
import sys
from pathlib import Path

p = _sage_const_65537 
ell = _sage_const_97 
D = _sage_const_96 
m_val = _sage_const_50731 
cofactor = m_val // ell  # 523
g = _sage_const_5   # primitive root mod 97
g_inv = inverse_mod(g, ell)

print("=" * _sage_const_70 )
print("Mixed-Radix DIF Verification for D=96=32×3")
print(f"p={p}, ell={ell}, m={m_val}")
print("=" * _sage_const_70 )

# Setup ring
Fp = GF(p)
Rpoly = PolynomialRing(Fp, names=('y',)); (y,) = Rpoly._first_ngens(1)

# Recover G from dump (known from previous experiments)
G_coeffs = [_sage_const_1 , _sage_const_43 , _sage_const_1461 , _sage_const_58250 , _sage_const_9157 , _sage_const_9246 , _sage_const_59875 , _sage_const_13341 , _sage_const_31936 , _sage_const_43855 ,
            _sage_const_31936 , _sage_const_13341 , _sage_const_59875 , _sage_const_9246 , _sage_const_9157 , _sage_const_58250 , _sage_const_1461 , _sage_const_43 , _sage_const_1 ]
G = Rpoly(G_coeffs)
QR = Rpoly.quotient(G, 'w')
w = QR.gen()

# HElib reps and evaluation points
reps = [power_mod(g_inv, j, ell) for j in range(D)]
points = [w**((reps[j] * cofactor) % m_val) for j in range(D)]

# Build full Step2Matrix
print("\n[1] Building Step2Matrix (96×96 Vandermonde)...")
S = Matrix(QR, D, D)
for j in range(D):
    S[_sage_const_0 , j] = QR(_sage_const_1 )
for i in range(_sage_const_1 , D):
    for j in range(D):
        S[i, j] = S[i-_sage_const_1 , j] * points[j]
print("    Done.")

# ============================================================
# Stage 1: Radix-3 DIF (stride 32)
# ============================================================
print("\n[2] Building Stage 1: Radix-3 DIF (stride 32)...")

# omega_3: primitive cube root of unity
# -3 is NOT a QR mod p, so omega_3 is in F_{p^2} (not F_p)
# But F_{p^2} ⊂ F_{p^18} = QR, so we can find it in QR
# omega_3 = w^{(p^18-1)/3}
exp_3 = (p**_sage_const_18  - _sage_const_1 ) // _sage_const_3 
omega3 = w**exp_3
assert omega3**_sage_const_3  == QR(_sage_const_1 ), "omega3^3 != 1"
assert omega3 != QR(_sage_const_1 ), "omega3 is trivial"
# Verify it's in F_{p^2}: omega3^{p^2} == omega3
assert omega3**(p**_sage_const_2 ) == omega3, "omega3 not in F_{p^2}"
omega3_sq = omega3**_sage_const_2 
print(f"    omega_3 found in F_{{p^2}} (subset of F_{{p^18}}) ✓")
print(f"    omega_3 degree: {omega3.lift().degree()}")

# Build Stage 1 matrix: 96×96, diagonals at {0, 32, 64}
# M1[i][j] != 0 only if (j-i)%96 in {0, 32, 64}
# For group k (k=0,...,31): positions {k, k+32, k+64}
#   Y[k]    = X[k] + X[k+32] + X[k+64]
#   Y[k+32] = X[k] + omega_3*X[k+32] + omega_3^2*X[k+64]
#   Y[k+64] = X[k] + omega_3^2*X[k+32] + omega_3*X[k+64]

M_stage1 = Matrix(QR, D, D)
for k in range(_sage_const_32 ):
    # Row k: Y[k] = X[k] + X[k+32] + X[k+64]
    M_stage1[k, k] = QR(_sage_const_1 )
    M_stage1[k, k+_sage_const_32 ] = QR(_sage_const_1 )
    M_stage1[k, k+_sage_const_64 ] = QR(_sage_const_1 )
    # Row k+32: Y[k+32] = X[k] + omega_3*X[k+32] + omega_3^2*X[k+64]
    M_stage1[k+_sage_const_32 , k] = QR(_sage_const_1 )
    M_stage1[k+_sage_const_32 , k+_sage_const_32 ] = omega3
    M_stage1[k+_sage_const_32 , k+_sage_const_64 ] = omega3_sq
    # Row k+64: Y[k+64] = X[k] + omega_3^2*X[k+32] + omega_3*X[k+64]
    M_stage1[k+_sage_const_64 , k] = QR(_sage_const_1 )
    M_stage1[k+_sage_const_64 , k+_sage_const_32 ] = omega3_sq
    M_stage1[k+_sage_const_64 , k+_sage_const_64 ] = omega3

# Check diagonal offsets
s1_offsets = set()
for i in range(D):
    for j in range(D):
        if M_stage1[i,j] != QR(_sage_const_0 ):
            s1_offsets.add((j-i) % D)
print(f"    Stage 1 diagonal offsets: {sorted(s1_offsets)} ({len(s1_offsets)} diags)")

# ============================================================
# Stage 2-6: Radix-2 DIF (5 layers within each 32-block)
# ============================================================
print("\n[3] Building Stages 2-6: Radix-2 DIF (5 layers)...")

# omega_32: primitive 32nd root of unity in F_p
# 32 | p-1 = 65536 ✓
g_p = primitive_root(p)
omega32_val = power_mod(int(g_p), (p-_sage_const_1 )//_sage_const_32 , p)
omega32 = QR(Fp(omega32_val))
assert omega32**_sage_const_32  == QR(_sage_const_1 )
assert omega32**_sage_const_16  != QR(_sage_const_1 )
print(f"    omega_32 = {omega32_val}")

# Build 5 butterfly layers
# Layer l: stride s = 16, 8, 4, 2, 1
# Within each of 3 blocks (size 32), do butterfly with stride s
M_stages_radix2 = []
for layer, s in enumerate([_sage_const_16 , _sage_const_8 , _sage_const_4 , _sage_const_2 , _sage_const_1 ]):
    M_layer = Matrix(QR, D, D)
    # n = 2*s (butterfly size)
    n = _sage_const_2  * s
    # root for this layer: omega_32^{32/n} = omega_32^{32/(2s)}
    root_exp = _sage_const_32  // n
    root = omega32**root_exp  # primitive n-th root of unity

    for block in range(_sage_const_3 ):
        block_base = block * _sage_const_32 
        for seg_start in range(_sage_const_0 , _sage_const_32 , n):
            base = block_base + seg_start
            for q in range(s):
                # Butterfly: Y[base+q] = X[base+q] + twiddle*X[base+q+s]
                #            Y[base+q+s] = X[base+q] - twiddle*X[base+q+s]
                twiddle = root**q
                i_top = base + q
                i_bot = base + q + s
                M_layer[i_top, i_top] = QR(_sage_const_1 )
                M_layer[i_top, i_bot] = twiddle
                M_layer[i_bot, i_top] = QR(_sage_const_1 )
                M_layer[i_bot, i_bot] = -twiddle

    # Check offsets
    offsets = set()
    for i in range(D):
        for j in range(D):
            if M_layer[i,j] != QR(_sage_const_0 ):
                offsets.add((j-i) % D)
    M_stages_radix2.append(M_layer)
    print(f"    Layer {layer+_sage_const_1 } (stride {s:2d}): {len(offsets)} diags, offsets={sorted(offsets)}")

# ============================================================
# Verify: product of all stages == Step2Matrix (up to reordering)
# ============================================================
print("\n[4] Computing product of all stages...")
product = M_stage1
for M_layer in M_stages_radix2:
    product = M_layer * product

# Check if product == S (or some permutation of S)
print("    Checking if product == Step2Matrix...")
match = (product == S)
print(f"    Direct match: {match}")

if not match:
    # Check diagonal structure of product
    prod_offsets = set()
    for i in range(D):
        for j in range(D):
            if product[i,j] != QR(_sage_const_0 ):
                prod_offsets.add((j-i) % D)
    print(f"    Product has {len(prod_offsets)} non-zero diagonals")

    # Check if product is a permutation of S (reordered columns/rows)
    # The DIF output is in bit-reversed order within each block
    # Try to find the permutation
    print("    Checking if product is a row/column permutation of S...")

    # Check: is there a permutation P such that product = S * P?
    # i.e., columns of product are a permutation of columns of S
    # Check column 0 of product against all columns of S
    col0_prod = [product[i, _sage_const_0 ] for i in range(D)]
    found_perm = False
    for j in range(D):
        col_j_S = [S[i, j] for i in range(D)]
        if col0_prod == col_j_S:
            print(f"    product[:,0] matches S[:,{j}]")
            found_perm = True
            break

    if not found_perm:
        # Maybe it's product = P * S (row permutation)
        # Or maybe we need twiddle factors between stages
        print("    No simple permutation found.")
        print("    The Mixed-Radix DIF needs TWIDDLE FACTORS between stages!")
        print()
        print("    Correct decomposition: S = Reorder * DIF_radix2 * Twiddle * DIF_radix3")
        print("    The twiddle matrix accounts for the mixed-radix structure.")

# ============================================================
# Add twiddle factors and reorder
# ============================================================
print("\n[5] Adding twiddle factors...")

# In Cooley-Tukey mixed-radix FFT for N = N1*N2:
# DFT_N = (DFT_N1 ⊗ I_N2) * Twiddle * (I_N1 ⊗ DFT_N2) * Permutation
# For N=96, N1=3, N2=32:
# DFT_96 = (DFT_3 ⊗ I_32) * Twiddle * (I_3 ⊗ DFT_32) * P
#
# Twiddle[k] = omega_96^{k1*k2} where k = k1*32 + k2 (k1<3, k2<32)
# omega_96 = primitive 96th root of unity (in F_{p^2})

# Find omega_96 in F_{p^2}
# 96 | p^2-1 ✓ (verified earlier)
# omega_96 = (some element of F_{p^2})^{(p^2-1)/96}
# In our QR = F_{p^18}, we can find omega_96 as w^{(p^18-1)/96}...
# but that's in F_{p^18}. We need it in F_{p^2}.
# Actually omega_96 ∈ F_{p^2} iff 96 | p^2-1. Let's compute it.

# F_{p^2} is a subfield of F_{p^18} (since 2|18).
# An element x ∈ F_{p^18} is in F_{p^2} iff x^{p^2} = x.
# omega_96 = w^{(p^18-1)/96}
exp_96 = (p**_sage_const_18  - _sage_const_1 ) // _sage_const_96 
omega96 = w**exp_96
assert omega96**_sage_const_96  == QR(_sage_const_1 ), "omega96^96 != 1"
assert omega96**_sage_const_48  != QR(_sage_const_1 ), "omega96 has order < 96"
# Check if in F_{p^2}
in_Fp2 = (omega96**(p**_sage_const_2 ) == omega96)
print(f"    omega_96 found, in F_{{p^2}}: {in_Fp2}")

# Build twiddle matrix: diagonal, T[k1*32+k2, k1*32+k2] = omega_96^{k1*k2}
M_twiddle = Matrix(QR, D, D)
for k1 in range(_sage_const_3 ):
    for k2 in range(_sage_const_32 ):
        idx = k1 * _sage_const_32  + k2
        M_twiddle[idx, idx] = omega96**(k1 * k2)

# Build permutation (CRT reorder for Good-Thomas / Cooley-Tukey)
# Input index j maps to (j mod 3, j mod 32) in the 3×32 array
# Output index: k1*32 + k2 where k1 = j mod 3, k2 = j mod 32
# But we need to match HElib's ordering...
# Actually for Cooley-Tukey: input in natural order, output in mixed-radix order
# P maps: position j → position (j%3)*32 + (j%32)... but j%3 and j%32 don't uniquely determine j
# since gcd(3,32)=1, CRT gives: j ↔ (j mod 3, j mod 32) bijectively for j in {0,...,95}

# CRT permutation: j → k where k = (j mod 3)*32 + (j mod 32)...
# No, the CRT isomorphism is: j mod 96 ↔ (j mod 32, j mod 3) via CRT
# Inverse: given (a, b) with a<32, b<3, find j<96 with j≡a mod 32, j≡b mod 3
# j = a*3*inv(3,32) + b*32*inv(32,3) mod 96
# inv(3,32) = 11 (3*11=33≡1 mod 32)
# inv(32,3) = 2 (32*2=64≡1 mod 3)
# j = a*33 + b*64 mod 96

inv_3_32 = inverse_mod(_sage_const_3 , _sage_const_32 )  # = 11
inv_32_3 = inverse_mod(_sage_const_32 , _sage_const_3 )  # = 2

P_perm = Matrix(QR, D, D)
for j in range(D):
    a = j % _sage_const_32   # k2
    b = j % _sage_const_3    # k1
    k = b * _sage_const_32  + a  # target position in (k1, k2) layout
    P_perm[k, j] = QR(_sage_const_1 )

# Now: S should equal (DFT_3 ⊗ I_32) * Twiddle * (I_3 ⊗ DFT_32) * P
# But our DFT_3 and DFT_32 are at SPECIFIC points (not generic roots of unity)
# The Step2Matrix evaluates at points[j] = zeta_97^{reps[j]*cofactor}
# These are NOT omega_96^j !

# The issue: Step2Matrix is a Vandermonde at SPECIFIC points,
# not a standard DFT at roots of unity.
# Mixed-radix NTT only works for standard DFT (at equally-spaced roots).

# For our case: points[j] = zeta_97^{g_inv^j * cofactor}
# These are 97-th roots of unity in a SPECIFIC order (determined by g_inv).
# They are NOT 96-th roots of unity!

print()
print("    ISSUE: Step2Matrix points are 97-th roots of unity,")
print("    not 96-th roots of unity. Standard NTT decomposition")
print("    does not directly apply.")
print()
print("    The Rader algorithm converts 97-point DFT (at 97-th roots)")
print("    into 96-point cyclic convolution, THEN applies NTT.")
print("    Our Mixed-Radix approach needs to work AFTER Rader conversion.")
print()
print("    Correct pipeline:")
print("    Step2Matrix = CRT_output * InvDIF32 * BlockMix * DIF32 * CRT_input")
print("    (This is exactly what ThinStep2Rader97Exec does!)")
print()
print("    Our optimization: replace the DIF32 stages with Mixed-Radix stages")
print("    that have FEWER total diagonals.")
print()

# Actually, let's count the diagonals in the EXISTING Rader/DIF approach:
print("=== Existing Rader/DIF diagonal count ===")
print("  CRT_input: 96 diags (permutation-like)")
print("  DIF32 (5 layers): each 2 diags × 3 blocks = 6 diags per layer")
print("    But in cyclic-96 representation: offsets depend on stride")
print("  BlockMix: 3 diags (block-diagonal)")
print("  InvDIF32 (5 layers): same as DIF32")
print("  CRT_output: 96 diags")
print()
print("  Total stages: 1 + 5 + 1 + 5 + 1 = 13 stages")
print("  Each stage has 2-6 diags → total ~13 stages with few diags each")
print("  But 13 HOISTINGS is expensive!")
print()
print("  vs our Mixed-Radix (if it worked):")
print("  Stage 1 (radix-3): 3 diags, 1 hoisting")
print("  Stages 2-6 (radix-2): 2 diags each, 5 hoistings")
print("  Total: 6 stages, 6 hoistings")
print("  vs Rader: 13 stages, 13 hoistings")
print("  Hoisting savings: 13->6 = 54% fewer hoistings!")

