"""
Verify the ACTUAL matrix structure of each tower layer.
Key question: does each layer produce a matrix with only 2-4 non-zero diagonals?
If yes, then hoisting + few rotations per layer → faster than BSGS.
"""


# This file was *autogenerated* from the file peikert_tower_matrix_verify.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65537 = Integer(65537); _sage_const_97 = Integer(97); _sage_const_96 = Integer(96); _sage_const_70 = Integer(70); _sage_const_50 = Integer(50); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_32 = Integer(32); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_64 = Integer(64); _sage_const_1 = Integer(1)
p = _sage_const_65537 
ell = _sage_const_97 
D = _sage_const_96 

Fp = GF(p)
g = primitive_root(ell)  # g=5

print("="*_sage_const_70 )
print("Tower Layer Matrix Structure Verification")
print("="*_sage_const_70 )
print()

# The Galois group Z/96Z acts on the D=96 slots.
# Automorphism σ^k permutes slot j → slot (j+k mod 96) [additive notation]
# In multiplicative notation: σ^k maps ζ_97 → ζ_97^{g^k}

# The CRT basis c̃ has entries indexed by ℓ ∈ G = Z/96Z
# c_ℓ = idempotent for slot ℓ

# Tower: Z/96Z ⊃ H_1 ⊃ H_2 ⊃ ... ⊃ {0}
# H_i = subgroup of order 96/prod(degrees up to i)

# For our tower [2,2,2,2,2,3]:
# H_0 = Z/96Z (order 96) - base field
# H_1 = 2·Z/96Z (order 48) - after first degree-2 step
# H_2 = 4·Z/96Z (order 24)
# H_3 = 8·Z/96Z (order 12)
# H_4 = 16·Z/96Z (order 6)
# H_5 = 32·Z/96Z (order 3)
# H_6 = {0} (order 1) - full field

# At each layer i, the transform T_i maps between bases of K_i/K_{i-1}
# The matrix of T_i (in the slot representation) has the form:
#   I_{|H_i|} ⊗ T_small
# where T_small is a deg(K_i/K_{i-1}) × deg(K_i/K_{i-1}) matrix

# In the SLOT representation (cyclic-D), this becomes:
# A block-diagonal matrix with |H_i| blocks, each of size d_i = deg(K_i/K_{i-1})
# The blocks are at positions determined by the cosets of H_i

# For the HOMOMORPHIC evaluation:
# Each layer needs automorphisms σ^t for t in the transversal T_i
# T_i = coset representatives of H_{i-1}/H_i

# Let's compute the diagonal structure for each layer

print("Layer-by-layer diagonal analysis:")
print("-"*_sage_const_50 )

subgroup_generators = [_sage_const_2 , _sage_const_4 , _sage_const_8 , _sage_const_16 , _sage_const_32 , _sage_const_96 ]  # generators of H_1,...,H_6
# H_i = <subgroup_generators[i-1]> in Z/96Z

total_diags = _sage_const_0 
for layer_idx in range(_sage_const_6 ):
    if layer_idx < _sage_const_5 :
        d_i = _sage_const_2   # degree of this layer
        # H_{layer_idx} = <2^layer_idx> · Z/96Z
        # H_{layer_idx+1} = <2^{layer_idx+1}> · Z/96Z
        # Transversal T = {0, 2^layer_idx} (mod 96)
        stride = _sage_const_2 **layer_idx
        T = [_sage_const_0 , stride]
    else:
        d_i = _sage_const_3   # degree of last layer
        # H_5 = <32> = {0, 32, 64}
        # H_6 = {0}
        # Transversal T = {0, 32, 64}... no
        # Actually T is coset reps of H_5/H_6 = {0,32,64}/{0} = {0,32,64}
        T = [_sage_const_0 , _sage_const_32 , _sage_const_64 ]
    
    # The diagonal offsets in the D×D matrix are:
    # offset = t' - t (mod D) for t, t' ∈ T
    offsets = set()
    for t1 in T:
        for t2 in T:
            offsets.add((t2 - t1) % D)
    
    nontrivial = offsets - {_sage_const_0 }
    total_diags += len(nontrivial)
    
    print(f"  Layer {layer_idx+_sage_const_1 } (degree {d_i}, stride {T[_sage_const_1 ] if len(T)>_sage_const_1  else '?'}):")
    print(f"    Transversal T = {T}")
    print(f"    Diagonal offsets = {sorted(offsets)}")
    print(f"    Non-trivial diagonals: {len(nontrivial)}")
    print(f"    → {len(nontrivial)} rotations + 1 hoisting per layer")
    print()

print(f"Total across all layers:")
print(f"  Hoistings: 6")
print(f"  Rotations: {total_diags}")
print(f"  Key-switches: 6 + {total_diags} = {_sage_const_6  + total_diags}")
print()

# Compare with BSGS
# BSGS for D=96: baby=10, giant=10
# Baby steps: 10 key-switches (to precompute rotations by 0,1,...,9)
# Giant steps: 10 key-switches (to apply rotation by 10,20,...,90)
# Total: 20 key-switches
# But within each giant step, the MulAdd operations are FREE (no KS)
# So effective: 10 (baby) + 10 (giant) = 20 key-switches

bsgs_baby = ceil(sqrt(D))
bsgs_giant = ceil(D / bsgs_baby)
bsgs_total = bsgs_baby + bsgs_giant

print(f"BSGS comparison:")
print(f"  Baby steps: {bsgs_baby} key-switches")
print(f"  Giant steps: {bsgs_giant} key-switches")
print(f"  Total: {bsgs_total} key-switches")
print()

tower_total = _sage_const_6  + total_diags
print(f"═══════════════════════════════════════════")
print(f"FINAL COMPARISON:")
print(f"  Tower: {tower_total} operations ({_sage_const_6 } hoistings + {total_diags} rotations)")
print(f"  BSGS:  {bsgs_total} operations ({bsgs_baby} baby + {bsgs_giant} giant)")
print(f"  Speedup: {bsgs_total}/{tower_total} = {float(bsgs_total/tower_total):.2f}x")
print(f"═══════════════════════════════════════════")
print()

if tower_total < bsgs_total:
    print("✓ TOWER IS FASTER (fewer total key-switch operations)")
else:
    print("✗ BSGS is still faster")

print()
print("CRITICAL NOTE:")
print("  In BSGS, baby-step rotations are PRECOMPUTED (stored as Ctxt objects)")
print("  Then giant-step MulAdd is just constant×Ctxt + Ctxt (no key-switch)")
print("  So BSGS effective cost = baby_KS + giant_KS = 20 key-switches")
print()
print("  In Tower, each layer does 1 hoisting + few rotations")
print("  The rotations AFTER hoisting are cheap (use precomputed decomposition)")
print("  So Tower effective cost = 6 hoistings + 14 cheap rotations")
print()
print("  If hoisting ≈ key-switch cost, and rotation << key-switch:")
print(f"    Tower: ~6 expensive + 14 cheap operations")
print(f"    BSGS:  ~20 expensive operations (baby+giant are all key-switches)")
print(f"    → Tower could be ~3x faster!")

