

# This file was *autogenerated* from the file tower_verify_v2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65537 = Integer(65537); _sage_const_97 = Integer(97); _sage_const_96 = Integer(96); _sage_const_50731 = Integer(50731); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1); _sage_const_43 = Integer(43); _sage_const_1461 = Integer(1461); _sage_const_58250 = Integer(58250); _sage_const_9157 = Integer(9157); _sage_const_9246 = Integer(9246); _sage_const_59875 = Integer(59875); _sage_const_13341 = Integer(13341); _sage_const_31936 = Integer(31936); _sage_const_43855 = Integer(43855); _sage_const_18 = Integer(18); _sage_const_3 = Integer(3); _sage_const_32 = Integer(32); _sage_const_42 = Integer(42); _sage_const_0 = Integer(0); _sage_const_64 = Integer(64); _sage_const_2 = Integer(2); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4)
p = _sage_const_65537 
ell = _sage_const_97 
D = _sage_const_96 
m_val = _sage_const_50731 
cofactor = m_val // ell
g_prim = _sage_const_5 
g_inv = inverse_mod(g_prim, ell)

Fp = GF(p)
Rpoly = PolynomialRing(Fp, names=('y',)); (y,) = Rpoly._first_ngens(1)
G_coeffs = [_sage_const_1 , _sage_const_43 , _sage_const_1461 , _sage_const_58250 , _sage_const_9157 , _sage_const_9246 , _sage_const_59875 , _sage_const_13341 , _sage_const_31936 , _sage_const_43855 ,
            _sage_const_31936 , _sage_const_13341 , _sage_const_59875 , _sage_const_9246 , _sage_const_9157 , _sage_const_58250 , _sage_const_1461 , _sage_const_43 , _sage_const_1 ]
G = Rpoly(G_coeffs)
QR = Rpoly.quotient(G, 'w')
w = QR.gen()

reps = [power_mod(g_inv, j, ell) for j in range(D)]
points = [QR(Rpoly(reps[j] * cofactor, _sage_const_1 ) % G) for j in range(D)]

# omega_3 in QR (from mixedradix_verify.sage)
exp_3 = (p**Integer(_sage_const_18 ) - _sage_const_1 ) // _sage_const_3 
omega3 = w**exp_3
print(f"omega3^3 == 1: {omega3**_sage_const_3  == QR(_sage_const_1 )}")
print(f"omega3 != 1: {omega3 != QR(_sage_const_1 )}")

# omega_32 in F_p
g_p = primitive_root(p)
omega32_val = power_mod(int(g_p), (p-_sage_const_1 )//_sage_const_32 , p)
omega32 = QR(Fp(omega32_val))

print(f"omega32 = {omega32_val}")
print(f"omega32^32 == 1: {omega32**_sage_const_32  == QR(_sage_const_1 )}")

# Test: apply DIF layers to a test vector, compare with Step2Matrix
import random
random.seed(Integer(_sage_const_42 ))
test_vec = [QR(Fp(random.randint(_sage_const_0 , p-_sage_const_1 ))) for _ in range(D)]

# Apply Step2Matrix directly
result_S = []
for i in range(D):
    val = QR(_sage_const_0 )
    for j in range(D):
        val += points[j]**i * test_vec[j]
    result_S.append(val)

# Apply tower: Layer 1 (radix-3, stride 32) + Layers 2-6 (radix-2)
v = list(test_vec)

# Layer 1: radix-3 DIF (stride 32)
next_v = [QR(_sage_const_0 )] * D
for j in range(_sage_const_32 ):
    x0, x1, x2 = v[j], v[j+_sage_const_32 ], v[j+_sage_const_64 ]
    next_v[j]    = x0 + x1 + x2
    next_v[j+_sage_const_32 ] = x0 + omega3 * x1 + omega3**_sage_const_2  * x2
    next_v[j+_sage_const_64 ] = x0 + omega3**_sage_const_2  * x1 + omega3 * x2
v = next_v

# Layers 2-6: radix-2 DIF (strides 16, 8, 4, 2, 1) within each block of 32
for stride in [_sage_const_16 , _sage_const_8 , _sage_const_4 , _sage_const_2 , _sage_const_1 ]:
    n = _sage_const_2  * stride
    root = omega32**(_sage_const_32  // n)
    next_v = list(v)
    for block in range(_sage_const_3 ):
        bb = block * _sage_const_32 
        for seg in range(_sage_const_0 , _sage_const_32 , n):
            for q in range(stride):
                idx_top = bb + seg + q
                idx_bot = bb + seg + q + stride
                tw = root**q
                top = v[idx_top]
                bot = v[idx_bot]
                next_v[idx_top] = top + tw * bot
                next_v[idx_bot] = top - tw * bot
    v = next_v

result_tower = v

# Compare
match = all(result_tower[i] == result_S[i] for i in range(D))
print(f"\nDirect match (tower == S*vec): {match}")

if not match:
    diffs = sum(_sage_const_1  for i in range(D) if result_tower[i] != result_S[i])
    print(f"Differences: {diffs}/{D}")
    # The tower output is in DIF order (bit-reversed within blocks)
    # Try bit-reversal
    def bit_rev5(x):
        r = _sage_const_0 
        for _ in range(_sage_const_5 ):
            r = (r << _sage_const_1 ) | (x & _sage_const_1 )
            x >>= _sage_const_1 
        return r
    
    reordered = [QR(_sage_const_0 )] * D
    for block in range(_sage_const_3 ):
        for j in range(_sage_const_32 ):
            reordered[block*_sage_const_32  + bit_rev5(j)] = result_tower[block*_sage_const_32  + j]
    
    match2 = all(reordered[i] == result_S[i] for i in range(D))
    print(f"After bit-reversal in blocks: {match2}")
    
    if not match2:
        # Maybe the issue is that this DIF computes a DIFFERENT transform
        # (cyclic convolution, not the Vandermonde evaluation)
        # The DIF computes: Y[k] = Σ_j X[j] * ω^{jk}
        # But Step2Matrix computes: S[i][j] = points[j]^i
        # These are different unless points[j] = ω^j
        
        # Let's check what the DIF actually computes
        # DIF output Y[k] for block b:
        # Y[b*32 + k] = Σ_{j=0}^{31} (Σ_{b'} omega3^{b'*b} * X[b'*32+j]) * omega32^{jk}
        # This is a 2D DFT: first radix-3 across blocks, then radix-2 within blocks
        
        # The Step2Matrix evaluates at points[j] = w^{reps[j]*cofactor}
        # These are NOT ω_96^j (they're in Rader order)
        
        print("\nThe DIF computes a standard 2D DFT (radix-3 × radix-2)")
        print("The Step2Matrix evaluates at Rader-ordered points")
        print("They differ by the Rader permutation (CRT_in)")
        print()
        print("BUT: in Peikert-Pepin's framework, the CRT basis IS")
        print("already in the 'right' order for the tower decomposition.")
        print("The issue is that HElib's slot ordering uses the Rader order,")
        print("not the tower order.")
        print()
        print("Key question: can we reorder HElib's slots to match the tower?")
        print("This requires a permutation, which costs O(sqrt(D)) key-switches.")
        print("If we need this permutation, we're back to square one.")
        print()
        print("ALTERNATIVE: work directly with HElib's slot ordering")
        print("and compute the tower twiddle factors for THAT ordering.")
        print("This means the butterfly coefficients won't be standard")
        print("roots of unity, but arbitrary slot-ring elements.")
        print("The structure (2-3 diags per layer) is preserved!")

