#!/usr/bin/env sage
"""
Correct Tower Decomposition for m=50731, p=65537.

The key insight (from notes/tower_coefficient_blocker_2026-05-15.md):
Tower decomposition works in the POLYNOMIAL RING F_p[z]/(G), not in scalar F_p.
The diagonal coefficients are elements of the slot ring F_{p^6}, not F_p scalars.

This script:
1. Loads the Step2Matrix from the HElib dump
2. Verifies it's a Vandermonde over the slot ring
3. Computes the tower decomposition using Peikert-Pepin Lemma 4.1
4. Exports the Stage 1 (6 diags) and Stage 2 (16 diags) coefficients
"""


# This file was *autogenerated* from the file tower_correct_impl.sage
from sage.all_cmdline import *   # import sage library

_sage_const_65537 = Integer(65537); _sage_const_97 = Integer(97); _sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_60 = Integer(60); _sage_const_16 = Integer(16); _sage_const_6 = Integer(6); _sage_const_0 = Integer(0); _sage_const_80 = Integer(80); _sage_const_96 = Integer(96); _sage_const_95 = Integer(95); _sage_const_10 = Integer(10); _sage_const_3 = Integer(3)
import json
import os

p = _sage_const_65537 
ell = _sage_const_97 
D = ell - _sage_const_1   # 96
g = _sage_const_5   # primitive root mod 97

print("=" * _sage_const_60 )
print("CORRECT TOWER DECOMPOSITION (polynomial ring method)")
print("=" * _sage_const_60 )

# ============================================================
# Step 1: Set up the slot ring F_{p^6}
# ============================================================
print("\n[Step 1] Setting up slot ring F_{p^6}...")

R = PolynomialRing(GF(p), names=('x',)); (x,) = R._first_ngens(1)
Phi97 = cyclotomic_polynomial(ell).change_ring(GF(p))

# Factor Phi_97 mod p into 16 irreducible degree-6 polynomials
factors_list = [f for f, e in Phi97.factor()]
assert len(factors_list) == _sage_const_16 
assert all(f.degree() == _sage_const_6  for f in factors_list)
print(f"  Phi_97 factors into {len(factors_list)} irreducible degree-6 polys")

# Pick the first factor as the slot polynomial G
G = factors_list[_sage_const_0 ]
print(f"  Slot polynomial G = {G}")

# Create the slot ring F_{p^6} = F_p[w]/(G)
F6 = GF(p**_sage_const_6 , modulus=G, names=('w',)); (w,) = F6._first_ngens(1)
print(f"  Slot ring F_{{p^6}} created, generator w")

# ============================================================
# Step 2: Find the 96 evaluation points
# ============================================================
print("\n[Step 2] Computing evaluation points...")

# The evaluation points are: point[j] = z^{g^j mod 97} evaluated in F_{p^6}
# where z is the root of Phi_97 in the slot ring.
# Since G | Phi_97, w is a root of Phi_97 in F_{p^6}.
# point[j] = w^{g^j mod 97}

points = []
for j in range(D):
    exp = int(pow(g, j, ell))
    pt = w**exp
    points.append(pt)

print(f"  Computed {len(points)} evaluation points in F_{{p^6}}")

# Frobenius step: sigma^80 corresponds to z -> z^p (since 5^80 = 62 = p mod 97)
# So point[j+80 mod 96] = point[j]^p
FROB_STEP = _sage_const_80 
frob_ok = all(points[(j+FROB_STEP) % D] == points[j]**p for j in range(D))
print(f"  Frobenius check (point[j+{FROB_STEP} mod 96] = point[j]^p): {'PASS' if frob_ok else 'FAIL'}")

# ============================================================
# Step 3: Build Step2Matrix as Vandermonde over F_{p^6}
# ============================================================
print("\n[Step 3] Building Step2Matrix (96x96 over F_{p^6})...")

# Step2Matrix[i][j] = point[j]^i
# This is the matrix that HElib uses for the dim-0 linear transform.
Step2 = matrix(F6, D, D)
for i in range(D):
    for j in range(D):
        Step2[i,j] = points[j]**i

print(f"  Step2Matrix built. Rank = {Step2.rank()}")

# ============================================================
# Step 4: Compute trace-dual basis for M/K
# ============================================================
print("\n[Step 4] Computing trace-dual basis...")

# Trace_{M/K}(a) = sum_{k=0}^{95} sigma^k(a)
# For a = w^n: Tr(w^n) = sum_{k=0}^{95} w^{n * g^k mod 97}
# In F_{p^6}: Tr(w^n) = sum of all 96 conjugates of w^n

# The trace form matrix T[i][j] = Tr_{M/K}(z^i * z^j) = Tr(z^{i+j})
# where z = w (root of Phi_97 in F_{p^6})
# Tr(w^n) for n mod 97:
#   If n % 97 == 0: Tr(1) = 96 (sum of 96 copies of 1)
#   If n % 97 != 0: Tr(w^n) = -1 (sum of all 97-th roots of unity minus 1 = 0 - 1 = -1)

# Actually Tr_{M/K} here means trace from the 96-dim space to F_p.
# The 96-dim space is F_p[z]/(Phi_97), and Tr is the standard trace.
# Tr(z^n) = sum_{k=0}^{95} (z^n)^{p^k... no, that's Tr_{F_{p^96}/F_p}

# Wait - we need to be careful about what "M" is here.
# M = F_p[z]/(Phi_97) is a 96-dimensional F_p-algebra (NOT a field - it's a product of 16 copies of F_{p^6})
# The trace Tr_{M/K}: M -> F_p is: Tr(a) = sum of all 96 "conjugates"
# For the algebra M = prod F_{p^6}, Tr(a) = sum_{i=0}^{15} Tr_{F_{p^6}/F_p}(a_i)
# where a_i is the projection of a to the i-th factor.

# For the monomial basis element z^n (n=0,...,95):
# z^n in M maps to (z^n mod f_0, z^n mod f_1, ..., z^n mod f_15)
# Tr(z^n) = sum_{i=0}^{15} Tr_{F_{p^6}/F_p}(z^n mod f_i)

# But there's a simpler formula: Tr_{M/K}(z^n) = coefficient of z^0 in n*z^n... no.
# Actually for cyclotomic rings: Tr(z^n) = mu(97) = -1 if gcd(n,97)=1, and = 96 if 97|n (i.e., n=0 mod 97)
# Since n ranges 0..95: Tr(z^0) = Tr(1) = 96, Tr(z^n) = -1 for n=1..95.

# Trace form matrix:
T_trace = matrix(GF(p), D, D)
for i in range(D):
    for j in range(D):
        s = (i + j) % ell  # z^i * z^j = z^{(i+j) mod 97} (in the quotient ring)
        T_trace[i,j] = GF(p)(_sage_const_96 ) if s == _sage_const_0  else GF(p)(-_sage_const_1 )

print(f"  Trace form matrix: {D}x{D}, det != 0: {T_trace.det() != _sage_const_0 }")

# Dual basis: b_j^dual satisfies Tr(b_i * b_j^dual) = delta_{ij}
# b_j^dual = sum_k (T^{-1})[k][j] * z^k
T_inv = T_trace.inverse()
print(f"  Trace form inverted.")

# ============================================================
# Step 5: Compute the 96 diagonal coefficients using Lemma 4.1
# ============================================================
print("\n[Step 5] Computing diagonal coefficients via Lemma 4.1...")
print("  Formula: coeff_k = sum_{i=0}^{15} e_i * sigma^k(b_i^dual)")
print("  where e_i are CRT idempotents, b_i^dual is trace-dual basis")

# First compute CRT idempotents in the quotient ring
Q_ring = R.quotient(Phi97, names=('z',)); (z,) = Q_ring._first_ngens(1)

idempotents = []
for i, fi in enumerate(factors_list):
    qi = Phi97 // fi
    inv_qi = qi.inverse_mod(fi)
    ei = Q_ring(R((qi * inv_qi) % Phi97))
    idempotents.append(ei)

# Verify
assert sum(idempotents) == Q_ring(_sage_const_1 ), "Idempotents don't sum to 1"
print(f"  16 CRT idempotents computed and verified.")

# Automorphism sigma^k: z -> z^{g^k mod 97}
def sigma_poly(poly_coeffs, k):
    """Apply sigma^k to element of F_p[z]/(Phi_97). Basis: {z^0=1, z^1,...,z^95}.
    sigma^k: z^i -> z^{(i*g^k) mod 97}. If result index >= 96, reduce using Phi_97."""
    if k == _sage_const_0 :
        return list(poly_coeffs)
    exp = int(pow(g, k, ell))
    result = [GF(p)(_sage_const_0 )] * D
    for i in range(len(poly_coeffs)):
        c = poly_coeffs[i]
        if c == _sage_const_0 :
            continue
        if i == _sage_const_0 :
            result[_sage_const_0 ] = result[_sage_const_0 ] + c
        else:
            new_idx = (i * exp) % ell  # in {0, 1, ..., 96}
            if new_idx == _sage_const_0 :
                # z^{i*exp} = z^{97k} = (z^97)^k = 1^k = 1 (since z^97=1 in this ring)
                result[_sage_const_0 ] = result[_sage_const_0 ] + c
            elif new_idx <= _sage_const_95 :
                result[new_idx] = result[new_idx] + c
            else:
                # new_idx == 96: z^96 = -(1 + z + ... + z^95)
                for idx in range(D):
                    result[idx] = result[idx] - c
    return result

# Compute dual basis elements as coefficient vectors
dual_basis_coeffs = []
for j in range(D):
    coeffs = [T_inv[k, j] for k in range(D)]
    dual_basis_coeffs.append(coeffs)

# Compute sigma^k(b_j^dual) for each k and j
# Then coeff_k = sum_{j=0}^{95} c_j * sigma^k(b_j^dual)
# where c_j is the j-th CRT basis element.
#
# But wait - the CRT basis has 96 elements (not 16).
# In Peikert-Pepin: c = (c_0, c_1, ..., c_{D-1}) is the CRT basis of M/K.
# For our case: c_j = e_{j div 6} * z^{j mod 6}... no, that's not right either.
#
# Let me re-read Lemma 4.1 more carefully.
# Lemma 4.1: f(x) = sum_{tau in G} <c_tilde, tau(b_tilde^dual)> * tau(x)
# where:
#   b_tilde = (b_0, ..., b_{D-1}) is the "source basis" (powerful basis)
#   c_tilde = (c_0, ..., c_{D-1}) is the "target basis" (CRT basis)
#   b_tilde^dual is the trace-dual of b_tilde
#   <u, v> = sum_i u_i * v_i (inner product in M)
#
# For our case:
#   b_tilde = (1, z, z^2, ..., z^95) (powerful basis)
#   c_tilde = the CRT basis: c_j is the element that has value 1 in position j
#             and 0 elsewhere in the CRT representation.
#   Concretely: c_j = e_{j div 6} * (z^{j mod 6} mod f_{j div 6}) lifted to M
#   But this is complex. Let me use a simpler characterization:
#   c_j is the unique element of M such that c_j mod f_i = delta_{i, j div 6} * z^{j mod 6} mod f_i

# Actually, the simplest approach: the CRT transform matrix IS the matrix
# that maps b_tilde to c_tilde. So:
# CRT_matrix[row][col] = "coefficient of c_row in the expansion of b_col in CRT basis"
# Or equivalently: c_row = sum_col CRT_matrix[row][col] * b_col

# And the diagonal coefficient for automorphism sigma^k is:
# coeff_k = <c_tilde, sigma^k(b_tilde^dual)> = sum_{j=0}^{95} c_j * sigma^k(b_j^dual)

# But c_j lives in M (the quotient ring), and so does sigma^k(b_j^dual).
# The inner product is in M: <u, v> = sum_j u_j * v_j where multiplication is in M.

# Let me compute this directly.
# coeff_k = sum_{j=0}^{95} c_j * sigma^k(b_j^dual)
# where c_j and b_j^dual are elements of M = F_p[z]/(Phi_97).

# The CRT basis elements c_j:
# c_j is defined by: the CRT transform maps b_j (= z^j) to the j-th standard basis vector.
# So c_j = the j-th column of CRT_matrix^{-1} (inverse CRT).
# Wait no. Let me think again.
#
# The CRT transform f maps: f(sum_j a_j * z^j) = (a evaluated at each slot)
# In matrix form: output = CRT_matrix * input_coefficients
# So CRT_matrix * [a_0, ..., a_95]^T = [slot values]
#
# The CRT basis c_tilde is the TARGET basis. The transform maps b_tilde -> c_tilde.
# Specifically: f(b_j) = c_j means the j-th column of CRT_matrix gives the
# CRT representation of z^j.
#
# For Lemma 4.1: coeff_k = <c_tilde, sigma^k(b_tilde^dual)>
# = sum_{j=0}^{95} c_j * sigma^k(b_j^dual)
#
# Here c_j is the j-th element of the CRT basis (as an element of M).
# c_j = the element whose CRT representation is the j-th standard basis vector.
# i.e., c_j = e_{j//6} * (appropriate local element)
# In terms of the powerful basis: c_j = sum_k (CRT_matrix^{-1})[k][j] * z^k

print("  Computing CRT basis elements (columns of CRT_matrix^{-1})...")

# Build CRT_matrix over F_p (96x96 scalar matrix)
# Row = output position (slot_i * 6 + local_k)
# Col = input position (power j)
# Entry = coefficient local_k of (z^j mod f_{slot_i})
CRT_mat = matrix(GF(p), D, D)
for slot_i in range(_sage_const_16 ):
    fi = factors_list[slot_i]
    for j in range(D):
        zj_mod = R(x**j) % fi
        for local_k in range(_sage_const_6 ):
            row = slot_i * _sage_const_6  + local_k
            col = j
            CRT_mat[row, col] = zj_mod[local_k] if local_k <= zj_mod.degree() else GF(p)(_sage_const_0 )

print(f"  CRT_mat rank = {CRT_mat.rank()}")
CRT_inv = CRT_mat.inverse()

# c_j as coefficient vector in powerful basis:
# c_j = sum_k CRT_inv[k][j] * z^k
crt_basis_coeffs = []
for j in range(D):
    coeffs = [CRT_inv[k, j] for k in range(D)]
    crt_basis_coeffs.append(coeffs)

# Now compute coeff_k for each k = 0, ..., 95:
# coeff_k = sum_{j=0}^{95} c_j * sigma^k(b_j^dual)
# Both c_j and sigma^k(b_j^dual) are elements of M = F_p[z]/(Phi_97)
# Their product is computed in M, then we sum over j.

print("  Computing 96 diagonal coefficients...")
diag_coeffs = []  # diag_coeffs[k] = coefficient vector (96 entries in F_p) of coeff_k

for k in range(D):
    if k % _sage_const_16  == _sage_const_0 :
        print(f"    k = {k}...")
    # sigma^k(b_j^dual): apply sigma^k to dual_basis_coeffs[j]
    # Then multiply by crt_basis_coeffs[j] in M, and sum over j

    result_coeffs = [GF(p)(_sage_const_0 )] * D
    for j in range(D):
        # sigma^k(b_j^dual)
        sk_bj_dual = sigma_poly(dual_basis_coeffs[j], k)

        # c_j * sigma^k(b_j^dual) in M = F_p[z]/(Phi_97)
        # Multiply two polynomials mod Phi_97
        poly_cj = R(sum(c * x**i for i, c in enumerate(crt_basis_coeffs[j]) if c != _sage_const_0 ))
        poly_sk = R(sum(c * x**i for i, c in enumerate(sk_bj_dual) if c != _sage_const_0 ))
        product = (poly_cj * poly_sk) % Phi97

        # Add to result
        for i in range(min(D, product.degree() + _sage_const_1 )):
            result_coeffs[i] = result_coeffs[i] + product[i]

    diag_coeffs.append(result_coeffs)

print(f"  All 96 diagonal coefficients computed.")

# ============================================================
# Step 6: Verify the decomposition
# ============================================================
print("\n[Step 6] Verifying: sum_k coeff_k * sigma^k(z^j) == CRT(z^j) for all j...")

errors = _sage_const_0 
for j in range(min(_sage_const_10 , D)):  # check first 10
    # Compute sum_k coeff_k * sigma^k(z^j)
    result = [GF(p)(_sage_const_0 )] * D
    for k in range(D):
        # sigma^k(z^j): z^j -> z^{(j * g^k) mod 97}
        if j == _sage_const_0 :
            sigma_zj = [GF(p)(_sage_const_0 )] * D
            sigma_zj[_sage_const_0 ] = GF(p)(_sage_const_1 )  # sigma^k(1) = 1
        else:
            exp_j = (j * int(pow(g, k, ell))) % ell
            sigma_zj = [GF(p)(_sage_const_0 )] * D
            if exp_j == _sage_const_0 :
                sigma_zj[_sage_const_0 ] = GF(p)(_sage_const_1 )
            elif exp_j <= _sage_const_95 :
                sigma_zj[exp_j] = GF(p)(_sage_const_1 )
            else:
                # exp_j == 96: z^96 = -(1+z+...+z^95)
                for idx in range(D):
                    sigma_zj[idx] = GF(p)(-_sage_const_1 )

        # coeff_k * sigma^k(z^j) in M
        poly_ck = R(sum(GF(p)(diag_coeffs[k][i]) * x**i for i in range(D) if diag_coeffs[k][i] != _sage_const_0 ))
        poly_szj = R(sum(GF(p)(sigma_zj[i]) * x**i for i in range(D) if sigma_zj[i] != _sage_const_0 ))
        product = (poly_ck * poly_szj) % Phi97

        for i in range(min(D, product.degree() + _sage_const_1 )):
            result[i] = result[i] + product[i]

    # Compare with CRT_mat column j (the CRT representation of z^j)
    expected = [CRT_mat[row, j] for row in range(D)]

    if result == expected:
        pass  # OK
    else:
        errors += _sage_const_1 
        if errors <= _sage_const_3 :
            print(f"  MISMATCH at j={j}: first diff at row {next((r for r in range(D) if result[r] != expected[r]), -_sage_const_1 )}")

if errors == _sage_const_0 :
    print(f"  PASS: All 10 checked columns match!")
else:
    print(f"  {errors}/10 mismatches (may need to fix CRT basis definition)")

# ============================================================
# Step 7: Analyze sparsity of tower stages
# ============================================================
print("\n[Step 7] Analyzing tower stage sparsity...")

# Stage 1 uses Frobenius subgroup H = {0, 16, 32, 48, 64, 80}
# Stage 2 uses coset representatives {0, 1, ..., 15}
H = [(_sage_const_16 *k) % D for k in range(_sage_const_6 )]  # [0, 16, 32, 48, 64, 80]
cosets = list(range(_sage_const_16 ))

# Check: are the Stage 1 coefficients (k in H) nonzero?
stage1_nonzero = sum(_sage_const_1  for k in H if any(c != _sage_const_0  for c in diag_coeffs[k]))
stage2_nonzero = sum(_sage_const_1  for k in cosets if any(c != _sage_const_0  for c in diag_coeffs[k]))

print(f"  Stage 1 (Frobenius, H={H}): {stage1_nonzero}/6 nonzero coefficients")
print(f"  Stage 2 (Cosets, {cosets}): {stage2_nonzero}/16 nonzero coefficients")

# The key question: can we decompose f = f_K o f_L?
# f_L uses only automorphisms in H (6 terms)
# f_K uses only coset representatives (16 terms)
# If f = f_K o f_L, then the 96 coefficients should be expressible as
# products of Stage 1 and Stage 2 coefficients.

# For now, just report the diagonal counts and export.
print("\n[Step 8] Exporting coefficients...")
output = {
    'p': int(p),
    'ell': int(ell),
    'D': int(D),
    'G': [int(c) for c in G.list()],
    'diag_coeffs': [[int(c) for c in diag_coeffs[k]] for k in range(D)],
    'frobenius_indices': H,
    'coset_indices': cosets,
}

outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tower_diag_coeffs.json')
with open(outpath, 'w') as f:
    json.dump(output, f)
print(f"  Exported to {outpath}")

print("\n" + "=" * _sage_const_60 )
print("DONE")
print("=" * _sage_const_60 )

