#!/usr/bin/env python3
"""Structure-level experiments for bootstrapping optimization routes.

The goal is not to claim ciphertext speedups from this file.  It produces
small, reproducible algebraic checks and operation-count estimates that decide
which route deserves a ciphertext prototype.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path

from linear_transform_factor_planner import PARAMS, factor, helib_bsgs_auts


@dataclass(frozen=True)
class TowerTraceResult:
    D: int
    factors: list[int]
    verified_trace_transitivity: bool
    direct_trace_automorphisms: int
    staged_relative_trace_automorphisms: int
    helib_bsgs_diagonal_automorphisms: int
    note: str


def composed_trace_exponents(D: int, factors: list[int]) -> set[int]:
    """Return Frobenius exponents generated by staged relative traces.

    If L/F has degree D and a tower with relative degrees in `factors`, trace
    transitivity says Tr_{L/F} is the composition of relative traces.  At a
    stage that lowers degree current -> current/r, the relative trace adds
    sigma^(j * lower_degree), j=0..r-1.  Composing stages forms all sums.
    """

    current_degree = D
    exponents = {0}
    for r in factors:
        if current_degree % r != 0:
            raise ValueError(f"factor {r} does not divide current degree {current_degree}")
        lower_degree = current_degree // r
        stage = {j * lower_degree for j in range(r)}
        exponents = {a + b for a in exponents for b in stage}
        current_degree = lower_degree
    return exponents


def tower_trace_result(D: int) -> TowerTraceResult:
    fs = factor(D)
    exps = composed_trace_exponents(D, fs)
    verified = exps == set(range(D))
    staged = sum(r - 1 for r in fs)
    bsgs = helib_bsgs_auts(D)["automorphisms"]
    if staged < bsgs:
        note = "promising for trace-like submaps, but must be fused with the actual EvalMap matrix"
    else:
        note = "not promising for this dimension versus existing BSGS-style diagonal execution"
    return TowerTraceResult(
        D=D,
        factors=fs,
        verified_trace_transitivity=verified,
        direct_trace_automorphisms=max(D - 1, 0),
        staged_relative_trace_automorphisms=staged,
        helib_bsgs_diagonal_automorphisms=bsgs,
        note=note,
    )


def good_thomas_rader_count(ell: int) -> dict:
    D = ell - 1
    fs = factor(D)
    dense_total = 2 * D * D

    # Match the existing plaintext_rader_evalmap.py counting model:
    # three mixed-radix DFTs plus pointwise multiply and normalization.  This
    # is an exact count for the current recursive prototype for ell=97, and a
    # conservative model for other smooth D.
    def mixed_dft_count(n: int) -> tuple[int, int]:
        if n == 1:
            return 0, 0
        r = min(x for x in range(2, n + 1) if n % x == 0)
        if r == n:
            return n * n, 2 * n * n
        m = n // r
        adds1, muls1 = mixed_dft_count(r)
        adds2, muls2 = mixed_dft_count(m)
        adds = m * adds1 + r * adds2
        muls = m * muls1 + r * muls2 + n
        return adds, muls

    dft_adds, dft_muls = mixed_dft_count(D)
    rader_adds = 3 * dft_adds + D
    rader_muls = 3 * dft_muls + 2 * D
    rader_total = rader_adds + rader_muls
    return {
        "ell": ell,
        "D": D,
        "factors": fs,
        "dense_total_ops": dense_total,
        "rader_mixed_radix_total_ops_model": rader_total,
        "ratio": rader_total / dense_total if dense_total else 1.0,
        "note": "plaintext operation model; ciphertext speedup needs fused executor",
    }


def pipeline_replacement_status() -> dict:
    return {
        "gbfv_native_slot_to_coeff": {
            "local_codebase": "external/fheanor",
            "tests": [
                "lin_transform::pow2::test_slots_to_coeffs_thin",
                "lin_transform::pow2::test_coeffs_to_slots_thin",
                "bgv::bootstrap::test_pow2_bgv_thin_bootstrapping_17",
                "bfv::bootstrap::test_pow2_bfv_thin_bootstrapping_17",
            ],
            "claim_boundary": (
                "validates a recent alternative bootstrapping/linear-transform "
                "pipeline, but is not directly comparable to the HElib p=65537 "
                "baseline without porting parameters and adding apples-to-apples timings"
            ),
        },
        "discrete_ckks_integer_cleaning": {
            "local_codebase": "not integrated",
            "tests": [
                "poly_eval::digit_extract::test_bounded_digit_retain_poly",
                "local SAT/sparse exact cleaner for p=65537, B=17, aux=256",
            ],
            "claim_boundary": (
                "current evidence supports bounded-support cleaning and null-polynomial "
                "sparsity, not a CKKS ciphertext replacement pipeline"
            ),
        },
    }


def build_report() -> dict:
    set_e = PARAMS["E"]
    tower = [tower_trace_result(abs(D)) for D in set_e.ords]
    rader = good_thomas_rader_count(set_e.mvec[0])
    return {
        "parameter_set": asdict(set_e),
        "route_A_tower_normal_basis": [asdict(x) for x in tower],
        "route_B_good_thomas_rader": rader,
        "route_C_and_D_external_pipeline_status": pipeline_replacement_status(),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    report = build_report()
    text = json.dumps(report, indent=2, sort_keys=True)
    if args.output:
        args.output.write_text(text + "\n")
    if args.json:
        print(text)
        return

    print("route A: tower/normal-basis trace model")
    for row in report["route_A_tower_normal_basis"]:
        print(
            f"  D={row['D']} factors={row['factors']} "
            f"verified={row['verified_trace_transitivity']} "
            f"direct={row['direct_trace_automorphisms']} "
            f"tower={row['staged_relative_trace_automorphisms']} "
            f"helib_bsgs_diag={row['helib_bsgs_diagonal_automorphisms']}"
        )
    r = report["route_B_good_thomas_rader"]
    print("route B: Good-Thomas/Rader plaintext model")
    print(
        f"  ell={r['ell']} D={r['D']} dense={r['dense_total_ops']} "
        f"rader={r['rader_mixed_radix_total_ops_model']} ratio={r['ratio']:.4f}"
    )
    print("route C/D: see JSON for external-pipeline test list and claim boundary")


if __name__ == "__main__":
    main()

