// compose_bench.cpp
// Benchmark: compose our order-four character filter with the Galois-structure
// polynomial evaluator of Okada-Player-Pohmann (AC'23, "[18]"), p = 257.
//
// Measures, all in the p_257 SlotRing context (plaintext modulus 257, e=1):
//   (a) THEIR native norm-based digit-extraction evaluator (P257CorrectionPolyEvaluator)
//       -- reference number for the "engine" it is specialized to.
//   (b) OUR P_A (deg 223) via a plain Paterson-Stockmeyer / BSGS evaluator in SEAL.
//   (c) OUR factored path: y = x^4, Q(y) (deg 55) via the same BSGS evaluator,
//       then result = 129*x + x^3*Q(y).
// Correctness: (c) is verified equal to (b) on all slots for support inputs
// x = eta*16 + lambda, |eta|,|lambda| <= 7 (digit semantics: result == lambda).
//
// NOTE ON FEASIBILITY (see final report): [18]'s PolyEvaluator is NOT an
// arbitrary-coefficient evaluator. It is hardwired to norm-form polynomials
// f(x) = x * N(beta - x) + correction(x) exploiting Galois/Frobenius structure.
// P_A and Q are generic polynomials, so we evaluate them with a plain in-SEAL
// BSGS routine to keep the P_A-vs-Q comparison internally consistent, and we
// report their native f only as an engine reference.

#include <iostream>
#include <vector>
#include <chrono>
#include <cmath>
#include <cassert>
#include "slots.h"
#include "seal/seal.h"
#include "bootstrapping.h"

using namespace seal;
using namespace std;

// ---- our filter coefficients (mod 257), generated by Lagrange interpolation ----
static const std::vector<uint64_t> PA_COEFFS = {0,129,0,91,0,0,0,65,0,0,0,245,0,0,0,23,0,0,0,253,0,0,0,38,0,0,0,251,0,0,0,198,0,0,0,170,0,0,0,166,0,0,0,23,0,0,0,194,0,0,0,31,0,0,0,88,0,0,0,233,0,0,0,48,0,0,0,233,0,0,0,152,0,0,0,153,0,0,0,7,0,0,0,31,0,0,0,153,0,0,0,34,0,0,0,157,0,0,0,83,0,0,0,206,0,0,0,154,0,0,0,60,0,0,0,207,0,0,0,99,0,0,0,106,0,0,0,230,0,0,0,196,0,0,0,218,0,0,0,246,0,0,0,155,0,0,0,100,0,0,0,76,0,0,0,86,0,0,0,146,0,0,0,81,0,0,0,74,0,0,0,206,0,0,0,184,0,0,0,163,0,0,0,48,0,0,0,228,0,0,0,16,0,0,0,112,0,0,0,9,0,0,0,53,0,0,0,175,0,0,0,252,0,0,0,72,0,0,0,23,0,0,0,224};
static const std::vector<uint64_t> Q_COEFFS = {91,65,245,23,253,38,251,198,170,166,23,194,31,88,233,48,233,152,153,7,31,153,34,157,83,206,154,60,207,99,106,230,196,218,246,155,100,76,86,146,81,74,206,184,163,48,228,16,112,9,53,175,252,72,23,224};
static const uint64_t C1 = 129;

// ============================================================================
// Plain Paterson-Stockmeyer / BSGS polynomial evaluator over SEAL BFV.
// Evaluates an arbitrary coefficient vector coeffs (c_0 + c_1 x + ...) on x_enc.
// Uses baby steps x^1..x^{bs} and giant steps (x^{bs})^k.
// Every relinearize is counted via log_relin() (increments kswitch_counter).
// ============================================================================
static void bsgs_eval(const std::vector<uint64_t>& coeffs, const Ciphertext& x_enc,
                      const Evaluator& eval, const RelinKeys& rk,
                      const Modulus& plain_mod, Ciphertext& dst) {
    size_t deg = coeffs.size() - 1;
    while (deg > 0 && coeffs[deg] == 0) --deg;
    size_t bs = (size_t)std::ceil(std::sqrt((double)(deg + 1)));
    if (bs < 1) bs = 1;
    size_t gs = (deg / bs) + 1;

    auto mkplain = [&](uint64_t v) { Plaintext p; p.resize(1); p[0] = plain_mod.reduce(v); return p; };

    std::cerr << "    [bsgs] deg=" << deg << " bs=" << bs << " gs=" << gs << std::flush;
    auto bt = std::chrono::steady_clock::now();
    // baby steps: powers[i] = x^{i+1}, i = 0..bs-1
    std::vector<Ciphertext> powers(bs);
    powers[0] = x_enc;
    for (size_t i = 1; i < bs; ++i) {
        eval.multiply(powers[i-1], x_enc, powers[i]);
        eval.relinearize_inplace(powers[i], rk); log_relin();
    }
    // giant base G = x^{bs}. Since powers[i] = x^{i+1}, powers[bs-1] = x^{bs} already.
    Ciphertext G = powers[bs-1];

    // giant powers Gp[k] = G^k, k = 0..gs-1 (Gp[0] unused as identity)
    std::vector<Ciphertext> Gp(gs);
    if (gs > 1) { Gp[1] = G; }
    for (size_t k = 2; k < gs; ++k) {
        eval.multiply(Gp[k-1], G, Gp[k]);
        eval.relinearize_inplace(Gp[k], rk); log_relin();
    }
    std::cerr << " | powers done +" << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-bt).count() << "ms" << std::flush;

    bool dst_set = false;
    for (size_t k = 0; k < gs; ++k) {
        // inner block: sum_{j=0..bs-1} c_{k*bs+j} * x^j
        Ciphertext block; bool block_set = false;
        uint64_t const_term = 0; bool has_const = false;
        for (size_t j = 0; j < bs; ++j) {
            size_t idx = k * bs + j;
            if (idx > deg) break;
            uint64_t c = coeffs[idx] % plain_mod.value();
            if (c == 0) continue;
            if (j == 0) { const_term = c; has_const = true; continue; }
            Plaintext cp = mkplain(c);
            Ciphertext term;
            eval.multiply_plain(powers[j-1], cp, term);
            if (!block_set) { block = term; block_set = true; }
            else eval.add_inplace(block, term);
        }
        // Fold the block constant term into the block ciphertext if the block has
        // ciphertext content. (For k>0 this becomes const*G^k after the giant multiply;
        // for k==0, G^0 = 1 so it is just the plain constant.)
        if (has_const && block_set) {
            Plaintext cp = mkplain(const_term);
            eval.add_plain_inplace(block, cp);
        }
        if (!block_set && !has_const) continue;

        if (k == 0) {
            if (block_set) {
                // block already includes the constant (folded above). Just take it.
                dst = block; dst_set = true;
            } else if (has_const) {
                // only a constant at position 0; handled after the loop via dst init.
                // (unused for P_A/Q which both have ciphertext content in block 0)
            }
        } else {
            if (!block_set) {
                // only a constant in this giant block: multiply const by G^k
                Plaintext cp = mkplain(const_term);
                Ciphertext term;
                eval.multiply_plain(Gp[k], cp, term);
                if (!dst_set) { dst = term; dst_set = true; }
                else eval.add_inplace(dst, term);
            } else {
                // block (incl. its constant) times G^k
                Ciphertext scaled;
                eval.multiply(block, Gp[k], scaled);
                eval.relinearize_inplace(scaled, rk); log_relin();
                if (!dst_set) { dst = scaled; dst_set = true; }
                else eval.add_inplace(dst, scaled);
            }
        }
    }
    std::cerr << " | giant done +" << std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now()-bt).count() << "ms\n" << std::flush;
    // handle the case where k==0 block had only a constant (deg-0 pathological); coeffs[0]:
    if (!dst_set) {
        // dst must equal c_0 * 1 ; emulate by multiply_plain on x then subtract? Simpler: encrypt not available here.
        // For our polynomials c_0 = 0 (P_A) or c_0 = 91 (Q, has j>0 terms too) so this path is unused.
        Plaintext cp = mkplain(coeffs[0]);
        eval.multiply_plain(x_enc, mkplain(0), dst); // dst = 0
        eval.add_plain_inplace(dst, cp);
    }
}

int main() {
    // ---- context: p_257 SlotRing, use e=1 (single-digit filter over F_257) ----
    std::shared_ptr<SlotRing> slot_ring_full = p_257_test_parameters(); // e=2, d=256, n=128
    SlotRing slot_ring = slot_ring_full->change_exponent(1);            // e=1, plaintext modulus 257

    EncryptionParameters parms(scheme_type::bfv);
    parms.set_poly_modulus_degree(slot_ring.N());
    parms.set_coeff_modulus(CoeffModulus::BFVDefault(slot_ring.N()));
    parms.set_plain_modulus(slot_ring.prime()); // 257
    SEALContext context(parms);
    const Modulus& plain_mod = context.first_context_data()->parms().plain_modulus();
    std::cout << "p=257 context, plaintext modulus " << plain_mod.value()
              << ", N=" << slot_ring.N() << ", slot_rank d=" << slot_ring.slot_rank()
              << ", slots n=" << slot_ring.slot_group_len() << std::endl;

    KeyGenerator keygen(context);
    SecretKey sk = keygen.secret_key();
    PublicKey pk; keygen.create_public_key(pk);
    RelinKeys rk; keygen.create_relin_keys(rk);

    Encryptor encryptor(context, pk);
    Evaluator evaluator(context);
    Decryptor decryptor(context, sk);

    // ---- build a CONSTANT-scalar test plaintext ----
    // A plaintext that is a pure scalar constant c (only coefficient 0 = c) puts value c
    // in EVERY slot. Because c is a scalar, all powers c^k stay scalar, so the homomorphic
    // result of any polynomial is again a pure constant plaintext {result} with only
    // coefficient 0 nonzero. This lets us read the result directly from coefficient 0 with
    // NO per-slot extract_slot_value automorphism (which is minute-scale at N=2^15).
    // We loop over all 225 support values x = eta*16+lambda to verify (b)==(c)==lambda.
    std::vector<std::tuple<int,int,long>> support; // (eta, lambda, x)
    for (int e = -7; e <= 7; ++e) for (int l = -7; l <= 7; ++l)
        support.push_back({e, l, (((e*16 + l) % 257) + 257) % 257});

    auto encrypt_const = [&](long c) {
        poly data; data.resize(1); data[0] = (uint64_t)((c % 257 + 257) % 257);
        Plaintext xp{ gsl::span<const uint64_t>(data) };
        Ciphertext ce; encryptor.encrypt(xp, ce); return ce;
    };
    // Decrypt to the full plaintext polynomial (fast: one decrypt, no per-slot automorphism).
    auto decrypt_poly = [&](const Ciphertext& ct) {
        Plaintext pt; decryptor.decrypt(ct, pt);
        poly rp(pt.data(), pt.data() + pt.coeff_count()); rp.resize(slot_ring.N());
        return rp;
    };
    // The scalar result of a constant-input computation is just coefficient 0.
    auto const_result = [&](const poly& rp) { return (long)(rp.size() ? rp[0] : 0); };

    // representative single input for the timed benchmark (support point eta=5, lambda=6 -> also matches their sample)
    long x_bench = (((5*16 + 6) % 257) + 257) % 257;
    Ciphertext x_enc = encrypt_const(x_bench);
    std::cout << "encrypted constant test input x=" << x_bench << "; noise budget "
              << decryptor.invariant_noise_budget(x_enc) << " bits" << std::endl;

    // ---- PROBES: verify basic constant arithmetic before the full benchmark ----
    {
        // probe 1: square. 86^2 mod 257 = 200
        Ciphertext sq; evaluator.square(x_enc, sq); evaluator.relinearize_inplace(sq, rk);
        poly sp = decrypt_poly(sq);
        std::cout << "PROBE square(86): coeff0=" << (sp.size()?sp[0]:0) << " expect " << (86*86%257)
                  << " ; nonzero-count=";
        size_t nz=0; for(auto v:sp) if(v) nz++; std::cout << nz << std::endl;
        // probe 2: bsgs on P(x)=x  (coeffs {0,1}) should return x
        Ciphertext idc; bsgs_eval(std::vector<uint64_t>{0,1}, x_enc, evaluator, rk, plain_mod, idc);
        poly ip = decrypt_poly(idc);
        std::cout << "PROBE bsgs[P(x)=x](86): coeff0=" << (ip.size()?ip[0]:0) << " expect 86" << std::endl;
        // probe 3: bsgs on P(x)=x^3 (coeffs {0,0,0,1}) should return 86^3 mod257
        Ciphertext c3c; bsgs_eval(std::vector<uint64_t>{0,0,0,1}, x_enc, evaluator, rk, plain_mod, c3c);
        poly c3p = decrypt_poly(c3c);
        std::cout << "PROBE bsgs[x^3](86): coeff0=" << (c3p.size()?c3p[0]:0) << " expect " << (86L*86*86%257) << std::endl << std::flush;
        // probe 4: Q(x^4) for x=86. x^4=165. Compute Q(165) mod257 in-loop expectation below.
        Ciphertext x4p; { Ciphertext s2; evaluator.square(x_enc,s2); evaluator.relinearize_inplace(s2,rk); evaluator.square(s2,x4p); evaluator.relinearize_inplace(x4p,rk);}
        poly x4pp = decrypt_poly(x4p);
        std::cout << "PROBE x^4(86): coeff0=" << (x4pp.size()?x4pp[0]:0) << " expect 165" << std::endl;
        Ciphertext qc; bsgs_eval(Q_COEFFS, x4p, evaluator, rk, plain_mod, qc);
        poly qpp = decrypt_poly(qc);
        std::cout << "PROBE Q(x^4=165)(86): coeff0=" << (qpp.size()?qpp[0]:0) << std::endl << std::flush;
    }

    // =====================================================================
    // (b) OUR P_A (deg 223) via BSGS
    // =====================================================================
    kswitch_counter = 0;
    auto t0 = std::chrono::steady_clock::now();
    Ciphertext pa_enc;
    bsgs_eval(PA_COEFFS, x_enc, evaluator, rk, plain_mod, pa_enc);
    auto t1 = std::chrono::steady_clock::now();
    size_t ks_pa = kswitch_counter;
    long ms_pa = std::chrono::duration_cast<std::chrono::milliseconds>(t1 - t0).count();
    std::cout << "[b] P_A direct (BSGS, deg 223): " << ms_pa << " ms, " << ks_pa
              << " key-switches, noise budget " << decryptor.invariant_noise_budget(pa_enc) << std::endl << std::flush;
    poly pa_poly = decrypt_poly(pa_enc);

    // =====================================================================
    // (c) FACTORED path: y = x^4 ; Q(y) (deg 55) via BSGS ; 129*x + x^3*Q(y)
    // =====================================================================
    kswitch_counter = 0;
    auto s0 = std::chrono::steady_clock::now();
    // x2 = x^2, x3 = x*x2, x4 = x2^2
    Ciphertext x2, x3, x4;
    evaluator.square(x_enc, x2);      evaluator.relinearize_inplace(x2, rk); log_relin();
    evaluator.multiply(x_enc, x2, x3);evaluator.relinearize_inplace(x3, rk); log_relin();
    evaluator.square(x2, x4);         evaluator.relinearize_inplace(x4, rk); log_relin();
    // Q(y), y = x4
    Ciphertext qy;
    bsgs_eval(Q_COEFFS, x4, evaluator, rk, plain_mod, qy);
    // result = 129*x + x^3 * Q(y)
    Ciphertext term1; // 129*x
    { Plaintext c1p; c1p.resize(1); c1p[0] = plain_mod.reduce(C1); evaluator.multiply_plain(x_enc, c1p, term1); }
    Ciphertext term2; // x^3 * Q(y)
    evaluator.multiply(x3, qy, term2); evaluator.relinearize_inplace(term2, rk); log_relin();
    Ciphertext fac_enc; evaluator.add(term1, term2, fac_enc);
    auto s1 = std::chrono::steady_clock::now();
    size_t ks_fac = kswitch_counter;
    long ms_fac = std::chrono::duration_cast<std::chrono::milliseconds>(s1 - s0).count();
    std::cout << "[c] factored Q path (y=x^4, Q deg 55): " << ms_fac << " ms, " << ks_fac
              << " key-switches, noise budget " << decryptor.invariant_noise_budget(fac_enc) << std::endl << std::flush;
    poly fac_poly = decrypt_poly(fac_enc);

    // =====================================================================
    // Correctness:
    //  (i)  (c) == (b): compare full decrypted plaintext polynomials directly
    //       (identical plaintexts <=> identical in every slot). One comparison, fast.
    //  (ii) digit semantics: decode a few slots and check result == lambda.
    // =====================================================================
    long pa_val = const_result(pa_poly);
    long fac_val = const_result(fac_poly);
    long lam_bench = (((6) % 257) + 257) % 257; // lambda of x_bench (eta=5,lambda=6)
    bool bc_match = (pa_poly == fac_poly);
    bool sem_ok = (pa_val == lam_bench) && (fac_val == lam_bench);
    std::cout << "correctness (i): full-plaintext (c)==(b): " << (bc_match ? "YES" : "NO") << std::endl;
    std::cout << "correctness (ii): x_bench=" << x_bench << " expected lambda=" << lam_bench
              << " ; P_A(x)=" << pa_val << " factored(x)=" << fac_val
              << " -> digit semantics: " << (sem_ok ? "YES" : "NO") << std::endl << std::flush;

    // Extra sweep: verify (b)==(c)==lambda on several more distinct support points
    // (constant-input eval reads coefficient 0 directly; no automorphism).
    {
        int extra_ok = 0, extra_tot = 0;
        std::vector<size_t> pick = {0, 30, 60, 112, 150, 200, 224}; // spread across the 225 support points
        for (size_t idx : pick) {
            int eta = std::get<0>(support[idx]);
            int lam = std::get<1>(support[idx]);
            long xv = std::get<2>(support[idx]);
            long lamm = ((lam % 257) + 257) % 257;
            Ciphertext xc = encrypt_const(xv);
            Ciphertext pc; bsgs_eval(PA_COEFFS, xc, evaluator, rk, plain_mod, pc);
            long pv = const_result(decrypt_poly(pc));
            // factored
            Ciphertext c2, c3, c4;
            evaluator.square(xc, c2); evaluator.relinearize_inplace(c2, rk); log_relin();
            evaluator.multiply(xc, c2, c3); evaluator.relinearize_inplace(c3, rk); log_relin();
            evaluator.square(c2, c4); evaluator.relinearize_inplace(c4, rk); log_relin();
            Ciphertext qc; bsgs_eval(Q_COEFFS, c4, evaluator, rk, plain_mod, qc);
            Ciphertext t1c; { Plaintext cp; cp.resize(1); cp[0]=plain_mod.reduce(C1); evaluator.multiply_plain(xc, cp, t1c); }
            Ciphertext t2c; evaluator.multiply(c3, qc, t2c); evaluator.relinearize_inplace(t2c, rk); log_relin();
            Ciphertext fc; evaluator.add(t1c, t2c, fc);
            long fv = const_result(decrypt_poly(fc));
            extra_tot++;
            bool ok = (pv == lamm) && (fv == lamm);
            if (ok) extra_ok++;
            std::cout << "  support idx " << idx << " (eta=" << eta << ",lam=" << lam << ",x=" << xv
                      << "): P_A=" << pv << " fac=" << fv << " exp=" << lamm
                      << (ok ? " OK" : " FAIL") << std::endl << std::flush;
        }
        std::cout << "extra sweep: " << extra_ok << "/" << extra_tot << " points correct" << std::endl;
    }

    // =====================================================================
    // (a) THEIR native norm-based evaluator (reference). Runs in its native
    //     e=2 context because their digit extractor is defined for p^e = 257^2.
    // =====================================================================
    std::cout << "--- reference: [18] native norm-based digit extractor (e=2 semantics) ---" << std::endl;
    {
        SlotRing sr2 = *slot_ring_full; // e=2
        EncryptionParameters parms2(scheme_type::bfv);
        parms2.set_poly_modulus_degree(sr2.N());
        parms2.set_coeff_modulus(CoeffModulus::BFVDefault(sr2.N()));
        parms2.set_plain_modulus(sr2.R().scalar_mod.value()); // 257^2
        SEALContext ctx2(parms2);
        KeyGenerator kg2(ctx2);
        SecretKey sk2 = kg2.secret_key();
        PublicKey pk2; kg2.create_public_key(pk2);
        RelinKeys rk2; kg2.create_relin_keys(rk2);
        std::unique_ptr<PolyEvaluator> de = p_257_test_parameters_digit_extractor(sr2);
        GaloisKeys gk2; kg2.create_galois_keys(de->galois_elements(), gk2);
        Encryptor enc2(ctx2, pk2);
        Evaluator ev2(ctx2);
        Decryptor dec2(ctx2, sk2);

        poly d2; poly_add(d2, sr2.from_slot_value({ (uint64_t)(5*257*257 + 6*257 - 3) }, 0), sr2.R().scalar_mod);
        Plaintext xp2{ gsl::span<const uint64_t>(d2) };
        Ciphertext xe2; enc2.encrypt(xp2, xe2);

        kswitch_counter = 0;
        auto r0 = std::chrono::steady_clock::now();
        Ciphertext re2; de->apply_ciphertext(xe2, ctx2, ev2, gk2, rk2, re2);
        auto r1 = std::chrono::steady_clock::now();
        size_t ks_f = kswitch_counter;
        long ms_f = std::chrono::duration_cast<std::chrono::milliseconds>(r1 - r0).count();
        std::cout << "[a] their native f (norm-based, deg 257): " << ms_f << " ms, " << ks_f
                  << " key-switches, noise budget " << dec2.invariant_noise_budget(re2) << std::endl;
    }

    // =====================================================================
    // Summary
    // =====================================================================
    std::cout << "\n========== SUMMARY (p=257) ==========" << std::endl;
    std::cout << "eval                          |   ms   |  KS | correct" << std::endl;
    std::cout << "[a] their f (norm, deg 257,e2)|  (see [a] line above)" << std::endl;
    std::cout << "[b] P_A direct  (deg 223)     | " << ms_pa  << "  | " << ks_pa  << "  | ref" << std::endl;
    std::cout << "[c] factored Q  (deg 55)      | " << ms_fac << "  | " << ks_fac << "  | " << (bc_match&&sem_ok ? "YES" : "NO") << std::endl;
    std::cout << "Rank observation: Q has deg 55, so a BSGS/Galois evaluator needs slot rank >= 56"
              << " (next power of two = 64), versus P_A deg 223 needing rank >= 224 (i.e. the full 256)."
              << " -> required slot rank divided by ~4." << std::endl;
    return 0;
}
